diff -Nru orig/Makefile patch/Makefile
--- orig/Makefile	2016-10-29 18:09:17.300108296 +0200
+++ patch/Makefile	2016-10-29 18:13:04.660111835 +0200
@@ -15,7 +15,7 @@
     $(OBJECTS_DIR)/player_ao.o 
 
 $(OBJECTS_DIR)/%.o: ./src/%.cpp 
-	g++ -D_PICO_LANG_DIR=\"/usr/share/pico/lang/\" -I. -I./svoxpico -Wall -g $(OPT_FLAG) -c $^ -o $@ 
+	g++ -D_PICO_LANG_DIR=\"/app/.apt/usr/share/pico/lang/\" -I. -I./svoxpico -Wall -g $(OPT_FLAG) -c $^ -o $@ 
 
 $(OBJECTS_DIR):
 	@[ -d $(OBJECTS_DIR) ] || mkdir $(OBJECTS_DIR)
